#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

exec < /dev/tty

echo "1)Ayman\n2)Angela\n3)Elias\nPick a number."

read name

echo "What do you wanna add to the devlog? (On one line)"

read devlog

now="$(date +"%r %m-%d-%Y")"

if [ "$name" -eq "1" ]; then
    echo "Ayman - $now - $devlog" >> devlog.txt;
    git add devlog.txt;
    exit 0;
fi

if [ "$name" -eq "2" ]; then
    echo "Angela - $now - $devlog" >> devlog.txt;
    git add devlog.txt;
    exit 0;
fi

if [ "$name" -eq "3" ]; then
    echo "Elias - $now - $devlog" >> devlog.txt;
    git add devlog.txt;
    exit 0;
fi

exit 1
